on:
  push:
    branches:
      - main
      - development
      - 'releases/**'
  pull_request:
      types: [opened, synchronize, reopened]

name: Code Analysis
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5.1.0 # Ex: v4.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
      with:
        projectBaseDir: ./src
        args: >
          --Dsonar.organization=${{ secrets.SONAR_CLOUD_ORG }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}